version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./social-app-be
    container_name: social-app-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      JWT_SECRET: 123e4567-e89b-12d3-a456-426614174000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./social-app-be:/app
      - /app/node_modules

  frontend:
    build: ./social-app-fe
    container_name: social-app-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8080
    depends_on:
      - backend

volumes:
  mongo-data: